import {
  Banknote,
  Beer,
  BookOpen,
  Briefcase,
  Bus,
  Car,
  Circle,
  CircleDollarSign,
  Coffee,
  CreditCard,
  Dog,
  Droplet,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Music,
  PiggyBank,
  Pizza,
  Plane,
  Plug,
  Receipt,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Star,
  Stethoscope,
  TrendingUp,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Zap,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  utensils: Utensils,
  "shopping-cart": ShoppingCart,
  "utensils-crossed": UtensilsCrossed,
  coffee: Coffee,
  car: Car,
  receipt: Receipt,
  zap: Zap,
  droplet: Droplet,
  wifi: Wifi,
  "shopping-bag": ShoppingBag,
  "heart-pulse": HeartPulse,
  "gamepad-2": Gamepad2,
  house: House,
  wallet: Wallet,
  gift: Gift,
  "trending-up": TrendingUp,
  "circle-dollar-sign": CircleDollarSign,
  landmark: Landmark,
  "piggy-bank": PiggyBank,
  plane: Plane,
  bus: Bus,
  fuel: Fuel,
  shirt: Shirt,
  dumbbell: Dumbbell,
  "graduation-cap": GraduationCap,
  briefcase: Briefcase,
  stethoscope: Stethoscope,
  pizza: Pizza,
  beer: Beer,
  music: Music,
  film: Film,
  "book-open": BookOpen,
  smartphone: Smartphone,
  laptop: Laptop,
  "credit-card": CreditCard,
  banknote: Banknote,
  heart: Heart,
  star: Star,
  dog: Dog,
  plug: Plug,
};

/** Names available in the category icon picker. */
export const ICON_CHOICES: string[] = Object.keys(MAP);

export function Icon({
  name,
  size = 16,
  className,
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  const Cmp = MAP[name] ?? Circle;
  return <Cmp size={size} className={className} strokeWidth={2} aria-hidden />;
}
