import {
  ArrowDownLeft,
  ArrowUpRight,
  Banknote,
  Beer,
  BookOpen,
  Briefcase,
  Bus,
  Car,
  CircleDollarSign,
  Coffee,
  CreditCard,
  Dog,
  Droplet,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Music,
  PiggyBank,
  Pizza,
  Plane,
  Plug,
  Receipt,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Star,
  Stethoscope,
  TrendingUp,
  User,
  Users,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Icon name (kebab-case, as stored on categories/subscriptions) → lucide glyph. */
export const MAP: Record<string, LucideIcon> = {
  "arrow-up-right": ArrowUpRight,
  "arrow-down-left": ArrowDownLeft,
  utensils: Utensils,
  "shopping-cart": ShoppingCart,
  "utensils-crossed": UtensilsCrossed,
  coffee: Coffee,
  car: Car,
  receipt: Receipt,
  zap: Zap,
  droplet: Droplet,
  wifi: Wifi,
  "shopping-bag": ShoppingBag,
  "heart-pulse": HeartPulse,
  "gamepad-2": Gamepad2,
  house: House,
  wallet: Wallet,
  gift: Gift,
  "trending-up": TrendingUp,
  "circle-dollar-sign": CircleDollarSign,
  landmark: Landmark,
  "piggy-bank": PiggyBank,
  plane: Plane,
  bus: Bus,
  fuel: Fuel,
  shirt: Shirt,
  dumbbell: Dumbbell,
  "graduation-cap": GraduationCap,
  briefcase: Briefcase,
  stethoscope: Stethoscope,
  pizza: Pizza,
  beer: Beer,
  music: Music,
  film: Film,
  "book-open": BookOpen,
  smartphone: Smartphone,
  laptop: Laptop,
  "credit-card": CreditCard,
  banknote: Banknote,
  heart: Heart,
  star: Star,
  dog: Dog,
  plug: Plug,
  user: User,
  users: Users,
};

/** Names available in entity icon pickers; utility-only UI glyphs stay out. */
const UTILITY_ICONS = new Set(["arrow-up-right", "arrow-down-left"]);
export const ICON_CHOICES: string[] = Object.keys(MAP).filter((name) => !UTILITY_ICONS.has(name));
